INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('37b80394-9a27-4765-b394-f0dd50f9ebee', 'document', 'document', 'ARRAY', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('c76ebe00-f34d-4520-97e7-025b5648aaa4', 'capabilities', 'capabilities', 'ARRAY', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('ef226816-9d57-43b4-bd91-24b0b084d814', 'canAddChildren', 'canAddChildren', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('15ab36ee-88fa-4534-b377-eaf2b9c51614', 'canAddMyDriveParent', 'canAddMyDriveParent', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('7d88d879-6130-4d47-a6c3-5e15e6ef84a2', 'canChangeCopyRequiresWriterPermission', 'canChangeCopyRequiresWriterPermission', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('d735d8af-2f70-4a45-a2bc-fae686626cd0', 'canChangeViewersCanCopyContent', 'canChangeViewersCanCopyContent', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('7199a3de-366f-4ceb-9cab-902581a38f21', 'canComment', 'canComment', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('a132d607-b682-4a39-a017-a292a4498051', 'canCopy', 'canCopy', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('21cb3196-d500-40a3-b511-5cf48615c234', 'canDelete', 'canDelete', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('5eaf8eaa-c016-4856-bfb8-81de382d08dc', 'canDeleteChildren', 'canDeleteChildren', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('dcf064d1-48df-4937-bbe6-cf0c7b0e224d', 'canDownload', 'canDownload', 'BOOLEAN', false);
INSERT INTO output_interface (id, label, name, param_type_enum, time) VALUES ('afd689b4-a1aa-468f-a6b9-decfca82f8c0', 'name', 'name', 'STRING', false);

INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canEdit', 'canEdit', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canListChildren', 'canListChildren', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canModifyContent', 'canModifyContent', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveChildrenOutOfDrive', 'canMoveChildrenOutOfDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveChildrenOutOfTeamDrive', 'canMoveChildrenOutOfTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveChildrenWithinDrive', 'canMoveChildrenWithinDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveChildrenWithinTeamDrive', 'canMoveChildrenWithinTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveItemIntoTeamDrive', 'canMoveItemIntoTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveItemOutOfDrive', 'canMoveItemOutOfDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveItemOutOfTeamDrive', 'canMoveItemOutOfTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveItemWithinDrive', 'canMoveItemWithinDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveItemWithinTeamDrive', 'canMoveItemWithinTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canMoveTeamDriveItem', 'canMoveTeamDriveItem', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canReadDrive', 'canReadDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canReadRevisions', 'canReadRevisions', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canReadTeamDrive', 'canReadTeamDrive', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canRemoveChildren', 'canRemoveChildren', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canRemoveMyDriveParent', 'canRemoveMyDriveParent', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canRename', 'canRename', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canShare', 'canShare', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canTrash', 'canTrash', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canTrashChildren', 'canTrashChildren', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('canUntrash', 'canUntrash', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('contentHints', 'contentHints', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('indexableText', 'indexableText', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('thumbnail', 'thumbnail', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('image', 'image', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('mimeType', 'mimeType', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('copyRequiresWriterPermission', 'copyRequiresWriterPermission', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('createdTime', 'createdTime', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('serialVersionUID', 'serialVersionUID', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('GMT', 'GMT', true, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_REGEX', 'RFC3339_REGEX', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_PATTERN', 'RFC3339_PATTERN', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('value', 'value', true, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('dateOnly', 'dateOnly', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('tzShift', 'tzShift', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('description', 'description', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('driveId', 'driveId', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('explicitlyTrashed', 'explicitlyTrashed', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('exportLinks', 'exportLinks', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('fileExtension', 'fileExtension', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('folderColorRgb', 'folderColorRgb', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('fullFileExtension', 'fullFileExtension', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('iconLink', 'iconLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('id', 'id', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('kind', 'kind', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('lastModifyingUser', 'lastModifyingUser', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('displayName', 'displayName', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('emailAddress', 'emailAddress', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('kind', 'kind', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('me', 'me', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('permissionId', 'permissionId', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('photoLink', 'photoLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('mimeType', 'mimeType', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('modifiedByMe', 'modifiedByMe', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('modifiedTime', 'modifiedTime', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('serialVersionUID', 'serialVersionUID', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('GMT', 'GMT', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_REGEX', 'RFC3339_REGEX', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_PATTERN', 'RFC3339_PATTERN', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('value', 'value', true, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('dateOnly', 'dateOnly', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('tzShift', 'tzShift', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('name', 'name', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('originalFilename', 'originalFilename', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('ownedByMe', 'ownedByMe', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('owners', 'owners', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('parents', 'parents', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('permissionIds', 'permissionIds', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('permissions', 'permissions', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('shared', 'shared', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('size', 'size', false, 'number');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('spaces', 'spaces', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('starred', 'starred', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('teamDriveId', 'teamDriveId', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('thumbnailLink', 'thumbnailLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('thumbnailVersion', 'thumbnailVersion', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('trashed', 'trashed', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('trashedTime', 'trashedTime', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('serialVersionUID', 'serialVersionUID', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('GMT', 'GMT', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_REGEX', 'RFC3339_REGEX', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('RFC3339_PATTERN', 'RFC3339_PATTERN', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('value', 'value', true, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('dateOnly', 'dateOnly', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('tzShift', 'tzShift', false, 'date');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('trashingUser', 'trashingUser', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('displayName', 'displayName', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('emailAddress', 'emailAddress', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('kind', 'kind', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('me', 'me', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('permissionId', 'permissionId', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('photoLink', 'photoLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('version', 'version', false, 'number');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('videoMediaMetadata', 'videoMediaMetadata', false, 'array');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('durationMillis', 'durationMillis', false, 'number');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('height', 'height', false, 'number');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('width', 'width', false, 'number');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('viewedByMe', 'viewedByMe', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('viewersCanCopyContent', 'viewersCanCopyContent', false, 'boolean');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('webContentLink', 'webContentLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('webViewLink', 'webViewLink', false, 'string');
INSERT INTO output_interface (label, name, time, param_type_enum) VALUES ('writersCanShare', 'writersCanShare', false, 'boolean');
