{
 "title": "Modula",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executor Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "__auto" },
    { "expr": "executor_queue_remaining_tasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor Active vs. Executor Max Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "executor_active", "legendFormat": "__auto" },
    { "expr": "executor_pool_max_threads", "legendFormat": "__auto" }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Kafka Consumer Records Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Threads Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}