name: Prepare image for deploy
# Для триггера из других репозиториев, когда настроим github app, то сможем использовать
#  docker-compose up -d --no-deps \${{ github.event.client_payload.service || '' }}
#on:
#  workflow_dispatch:
#  repository_dispatch:
#    types: [service-updated]
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Ubuntu Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd modula-core-infrastructure && 
            docker compose pull && 
            docker compose up -d
          "
